[Server]
Port = "8080"
ReadTimtOut = 60
WriteTimtOut = 60

[Session]
SessId = "SESSIONID"
Server = "127.0.0.1:6379"
Prefix = "redmaple_"
# Password = "redmaple_"
Expiration = 3600
Db=8

[Logger]
LogGoID = true
LogFile = "/opt/log/redmaple.log"
LogLevel = "debug"
Console = true
LogType = "roll"
LogMaxNum = 10
LogSize = 1
LogUnit = "GB"

[Db]
Driver = "mysql"
Username = "root"
Password = "jackking"
Protocol = "tcp"
Address = "127.0.0.1:3306"
Dbname = "redmaple"
Params = "?charset=utf8&strict=true&sql_notes=false&timeout=90s&collation=utf8_general_ci&parseTime=True&loc=Local"
Cache="memory"
# Cache=""

[Cache]
Type="memcache"
Servers = ["127.0.0.1:11211"]
[Cache.Config]
Prefix = "redmaple_"
Expiration = 0

[Template]
Static="static/"
Html="views/"
# Cache=false
Cache=true

[Route]
Controller="index"
Action="index"
